Remove 20 char limit for the vaultwarden admin token
truenas/charts pull request #1189
Opened 2023-05-07 23:25 UTC by jlsjonas

Hashed tokens (as per recommendation) will exceed the imposed 20 char limit.

Also see [Enabling admin page - Secure the `ADMIN_TOKEN`](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-admin-page#secure-the-admin_token)

2023-05-08 11:46 UTC, stavros-k requested changes
I think this was intended to be `min`. But now it's not easy to enforce that.
Agreed on removing
Please, make changes **only** in the vauiltwarden under library/ix-dev/community/vaultwarden and  also bump `version` in Chart.yaml

2023-05-08 18:16 UTC, stavros-k approved these changes

2023-05-09 11:04 UTC, Qubad786 approved these changes

2023-05-09 11:04 UTC, Qubad786 approved these changes

2023-05-09 11:04 UTC, merged