Adding smbclient to installation
truenas/charts pull request #1317
Opened 2023-06-30 09:29 UTC by T13nou

Tested & validated

2023-06-30 12:22 UTC, kmoore134 commented
@stavros-k - This looks correct to me. Please give it a review when you can. Thanks!

2023-06-30 12:22 UTC, kmoore134 commented
https://ixsystems.atlassian.net/browse/NAS-122739

2023-06-30 13:32 UTC, stavros-k requested changes
Hello, thanks for the pull request, I left some comments.
Code will need to be updated to account for the issues mentioned. thanks

2023-06-30 13:32 UTC, stavros-k commented on charts/nextcloud/1.6.31/templates/deployment.yaml
>          {{- end }}
Probes can't have multiple types defined at the same time.
eg if none of those are enabled, you will end up with 2 httpGet in startupProbe

Logic for probe type selection and script under exec type have to be merged.

2023-06-30 13:32 UTC, stavros-k commented on charts/nextcloud/1.6.31/templates/deployment.yaml
> +        {{- end }}
Only 1 postStart can exist. same with probes above.

Script must be merged with additional logic to handle both packages

2023-06-30 13:51 UTC, stavros-k commented
Also one more comment, all the changes must be done under `library/ix-dev/charts/nextcloud` directory.
Thanks

2023-07-04 20:53 UTC, stavros-k commented
Closing this as it's fixed in the linked PR.
Thanks!

2023-07-04 20:53 UTC, closed without merging