Change elastic registry to default dockerhub
truenas/charts pull request #1342
Opened 2023-07-07 20:06 UTC by BioQwer

2023-07-07 20:22 UTC, BioQwer commented
i did check is work. 
screenshot for proof
<img width="922" alt="image" src="https://github.com/truenas/charts/assets/5636129/fc33ff1a-2ca6-42f2-b43e-58877936365b">
<img width="1462" alt="image" src="https://github.com/truenas/charts/assets/5636129/0162b214-db03-4385-9596-96755eaa2ba3">

2023-07-10 10:19 UTC, stavros-k requested changes
Change should be done in `library/ix-dev/charts/diskoverdata`
Also bump the Chart.yaml `version` by `0.0.1`
Thanks

2023-07-11 15:39 UTC, BioQwer commented
@stavros-k i've done

2023-07-11 17:05 UTC, stavros-k approved these changes

2023-07-11 22:03 UTC, sonicaj approved these changes

2023-07-11 23:32 UTC, merged