Add name.com to charts
truenas/charts pull request #1716
Opened 2023-11-09 06:10 UTC by reederda

2023-11-09 07:48 UTC, stavros-k requested changes
Hello, please make changes only under `library/ix-dev/community/ddns-updater`
The directory you touched now is autogenerated.

Thanks

2023-11-10 03:26 UTC, reederda commented
Apologies. I've made the changes to the correct directory.

2023-11-10 04:44 UTC, stavros-k requested changes
Please revert changes on the `community/ddns-updater/1.0.16` directory.

2023-11-10 04:45 UTC, stavros-k commented on library/ix-dev/community/ddns-updater/ci/name-values.yaml
> +      nameTTL: 300
```suggestion
      nameTTL: 300

```

2023-11-10 04:45 UTC, stavros-k commented on library/ix-dev/community/ddns-updater/templates/dnsProviders/_name.tpl
> +*/}}
```suggestion
*/}}

```

2023-11-10 21:32 UTC, closed without merging