Photoprism: Add 'Host Network'
truenas/charts pull request #1802
Opened 2023-11-27 13:41 UTC by erdii

I've added a host network checkbox to the photoprism chart.
This makes photoprism reachable from tailscale, which I've also installed with host network enabled.

![image](https://github.com/truenas/charts/assets/5539202/63a809c7-04a1-49c9-899c-a176850065df)

2023-11-27 14:10 UTC, erdii commented
I hope I found all places that needed a change. Please let me know if I missed something.

2023-11-27 15:22 UTC, stavros-k requested changes
Please only make changes under `library/ix-dev/*`
The rest are auto generated.

Thanks

2023-11-27 22:12 UTC, erdii commented
Done :)

2023-11-28 13:53 UTC, stavros-k approved these changes

2023-11-28 15:04 UTC, sonicaj approved these changes

2023-11-28 15:04 UTC, merged