Fix chart name in section help
truenas/charts pull request #2159
Opened 2024-02-11 04:50 UTC by billm

Minio Storage section help incorrectly states that it is for Nextcloud.

2024-02-12 11:06 UTC, stavros-k requested changes
Please only do changes under `library/ix-dev/`. The change you have currently made won't persist and will be overwritten!

Thanks

2024-02-12 14:24 UTC, stavros-k reviewed
Please update patch `version` in Chart.yaml  (eg +0.0.1)

Thanks

2024-02-12 14:24 UTC, stavros-k commented on charts/minio/1.7.23/questions.yaml
> +    description: "Configure Storage for Minio"
```suggestion
    description: "Configure Storage for Nextcloud"
```

2024-02-12 14:29 UTC, stavros-k approved these changes

2024-02-12 14:29 UTC, stavros-k commented
Thanks!

2024-02-12 14:32 UTC, billm commented
Thanks for bearing with me on this!

2024-02-13 09:09 UTC, Qubad786 approved these changes
Thanks for the fix @billm, Approved 👍

2024-02-13 11:42 UTC, merged