Added Platform support to PalWorld Chart
truenas/charts pull request #2795
Opened 2024-09-05 18:43 UTC by pbtcameron

**Pull Request Summary:**

This pull request enhances the Helm configuration process for PalWorld by adding support for the new AllowConnectPlatform parameter. This parameter is required for configuring Xbox dedicated servers, a feature recently introduced in PalWorld.  The changes specifically focus on updating the Helm Questions to include prompts for configuring this new setting, ensuring seamless deployment of PalWorld on Kubernetes with Xbox server support.

**Key Changes:**

Helm Questions Update: The Helm Questions have been extended to incorporate the new AllowConnectPlatform parameter. This allows users to specify the desired platform connectivity options during Helm chart installation, enabling proper configuration of Xbox dedicated servers.

2024-09-10 11:11 UTC, stavros-k requested changes
Hello, please apply any changes only under the ix-dev/ directory.
Everything else is generated automatically.

Given that the migration is not written yet for this app, I can accept this change.
But this option should be also implemented in https://github.com/truenas/apps/blob/master/ix-dev/community/palworld/templates/docker-compose.yaml
In order to accept the PR here, otherwise the change can be done only on the truenas/apps repo.

Thanks

2024-09-10 14:04 UTC, pbtcameron commented
> Hello, please apply any changes only under the ix-dev/ directory. Everything else is generated automatically.
> 
> Given that the migration is not written yet for this app, I can accept this change. But this option should be also implemented in https://github.com/truenas/apps/blob/master/ix-dev/community/palworld/templates/docker-compose.yaml In order to accept the PR here, otherwise the change can be done only on the truenas/apps repo.
> 
> Thanks

Hi,
Sorry, I was unaware. I'll make the changes there and make a PR.

Thanks

2024-09-11 19:24 UTC, pbtcameron commented
> Hello, can you please remove changes in directories outside of `ix-dev` and sync changes we did on truenas/apps on this PR?
> 
> Thanks!

I've made the changes. Do I need to update the version to 1.0.5?

2024-09-12 11:06 UTC, stavros-k requested changes
Hello, I still see changes in directories outside of `ix-dev/`. Which shouldnt be happening.

Please revert those and only update files inside `ix-dev/`.

2024-09-12 11:51 UTC, pbtcameron commented
> Hello, I still see changes in directories outside of `ix-dev/`. Which shouldnt be happening.
> 
> Please revert those and only update files inside `ix-dev/`.

Sorry, I'm a bit confused. By `ix-dev/` is it in reference to `Palworld/1.0.4/`, `Palworld/` or a whole other folder altogether?

2024-09-12 11:53 UTC, stavros-k commented
Here: https://github.com/truenas/charts/tree/master/library/ix-dev/community/palworld

2024-09-12 13:12 UTC, pbtcameron commented
> Here: https://github.com/truenas/charts/tree/master/library/ix-dev/community/palworld

Thanks. I've applied the changes

2024-09-12 13:30 UTC, stavros-k reviewed
Thanks! Small nit, lets keep the naming convention here consistent!
And we should be good to go!

2024-09-12 13:30 UTC, stavros-k commented on library/ix-dev/community/palworld/questions.yaml
> +        - variable: allow_platform
```suggestion
        - variable: allowPlatform
```

2024-09-12 13:30 UTC, stavros-k commented on library/ix-dev/community/palworld/questions.yaml
> +                  Specify which platforms are allowed to connect
```suggestion
          description: Specify which platforms are allowed to connect
```

2024-09-12 13:30 UTC, stavros-k commented on library/ix-dev/community/palworld/templates/_palworld.tpl
> +              set_ini_value "AllowConnectPlatform" {{ .Values.palworldConfig.allow_platform }} false
```suggestion
              set_ini_value "AllowConnectPlatform" {{ .Values.palworldConfig.allowPlatform }} false
```

2024-09-12 13:30 UTC, stavros-k commented on library/ix-dev/community/palworld/values.yaml
> +  allow_platform: Steam
```suggestion
  allowPlatform: Steam
```

2024-09-12 13:37 UTC, stavros-k approved these changes

2024-09-12 13:48 UTC, merged

2024-09-17 10:01 UTC, HDR-Performance commented
Issue With Update for Palworld
attribute required

More info...
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 469, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 511, in __run_body
    rv = await self.method(*args)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 187, in nf
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 47, in nf
    res = await f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 116, in upgrade
    await self.upgrade_chart_release(job, release, options)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/upgrade.py", line 267, in upgrade_chart_release
    config, context = await self.middleware.call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/chart_release.py", line 353, in normalise_and_validate_values
    dict_obj = await self.middleware.call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1564, in call
    return await self._call(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1417, in _call
    return await methodobj(*prepared_call.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/chart_releases_linux/validation.py", line 54, in validate_values
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 70, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] values.palworldConfig.allowPlatform: attribute required

2024-09-17 18:29 UTC, HDR-Performance commented
how and where? in cnfg?

2024-09-17 19:49 UTC, stavros-k commented
> how and where? in cnfg?

You dont have to do anything.
Wait for the linked PR to be merged!
Thanks

2024-09-17 20:25 UTC, HDR-Performance commented
i cant update to the latest version is the issue nor is there an option for sever platform in 1.04 so it wont allow update to 1.05,

2024-09-17 20:43 UTC, stavros-k commented
Just wait for the linked PR to be merged. Its not yet.
You will be able to upgrade AFTER that.