Update README.md
truenas/charts pull request #2816
Opened 2024-09-17 20:51 UTC by Altlama

Please update so it is easy for everyone  tks

2024-09-17 21:02 UTC, stavros-k requested changes
There is no need to do all this `cd ..`.
a `/` before the passbolt will solve the issue.

Please also revert any changes you did on this file and apply (along with my suggestions) in the `library/ix-dev/community/passbolt/README.md` and app-readme.md files.

Thanks

2024-09-17 21:02 UTC, stavros-k commented on community/passbolt/1.2.12/README.md
> +/usr/share/php/passbolt/bin/cake passbolt register_user -r admin -u user@example.com -f first_name -l last_name
```suggestion
/usr/share/php/passbolt/bin/cake /passbolt register_user -r admin -u user@example.com -f first_name -l last_name
```

2024-09-17 21:02 UTC, stavros-k commented on community/passbolt/1.2.12/README.md
> +
```suggestion
```

2024-09-17 21:18 UTC, Altlama reviewed
looks good now?

2024-09-18 13:05 UTC, stavros-k commented
> looks good now?

Please only update these files:
`library/ix-dev/community/passbolt/README.md`
`library/ix-dev/community/passbolt/app-readme.md`

Thanks

2024-09-18 16:23 UTC, Altlama reviewed
looks good

2024-09-18 16:23 UTC, Altlama reviewed
looks good

2024-09-18 16:33 UTC, Altlama commented
Hello
The proposed solution for the directory  give the bellow error
$ /usr/share/php/passbolt/bin/cake /passbolt register_user -r admin -u ***@****.com -f first_name -l last_name

_**Unknown command `cake /passbolt`. Run `cake --help` to get the list of commands.
Did you mean: `passbolt`?

Other valid choices:

- version
- console
- passbolt**_

2024-09-18 16:37 UTC, stavros-k commented
I just tried the existing command in the docs (without the `/` and without doing `cd /`) and worked fine.
I'm not sure what issue you had that made you do all these extra steps.

See:


```
$  /usr/share/php/passbolt/bin/cake passbolt register_user -r admin -u s@s.com -f first_name -l last_name

     ____                  __          ____  
    / __ \____  _____ ____/ /_  ____  / / /_ 
   / /_/ / __ `/ ___/ ___/ __ \/ __ \/ / __/ 
  / ____/ /_/ (__  |__  ) /_/ / /_/ / / /    
 /_/    \__,_/____/____/_.___/\____/_/\__/   

 Open source password manager for teams
-------------------------------------------------------------------------------
User saved successfully.
To start registration follow the link provided in your mailbox or here: 
http://10.20.30.230:30097/setup/start/713f1feb-7a7b-4ced-b264-ba2e278f386f/6c954a8e-e59d-4cb7-a831-c23f18460089
$ pwd
/usr/share/php/passbolt
$ 
```

2024-09-18 16:49 UTC, Altlama commented
https://www.truenas.com/community/threads/passbolt-cant-change-initial-user.114501/
i have the same issue like in that post   i'm evaluating passbolt so i did redo the install and if i don't cd to that directory it is not working.  I run truenas scale Dragonfish-24.04.2.2

2024-09-18 16:55 UTC, stavros-k commented
Can you please show a step by step (with video or pictures) what you do and what you see?
Because the forum post, most of the issues is that the wrong pod was selected.

2024-09-18 17:19 UTC, Altlama commented
Sure  when i'm back next week
tks.

2024-10-02 19:00 UTC, closed without merging

2024-10-03 19:42 UTC, Altlama commented
Hello ,
I did remove all apps, K8s , IX app dataset and other apps dataset. Did re install and no issue that time. As scale is moving from kubernetes to Docker next release i will not involve myself more for now. Thank you for the support.