Allow special paths for host path mounts
truenas/charts pull request #542
Opened 2022-06-20 17:58 UTC by Qubad786

## Context

We should allow special paths like `/sys` or `/dev` or `/cluster` as being valid paths which can be mounted inside applications.

2022-06-20 17:58 UTC, bugclerk commented
Jira URL: https://jira.ixsystems.com/browse/NAS-116797

2022-06-20 18:02 UTC, yocalebo requested changes
How are we preventing applications from accessing the ctdb shared volume directory inside /cluster?

2022-06-20 18:03 UTC, Qubad786 commented
Can you clarify which path inside the cluster path should be restricted and i can add the changes?

2022-06-20 18:06 UTC, Qubad786 commented
Also does it mean that top level `/cluster` should not be allowed to mount as we don't want to allow mounting a subpath?
I am not sure how `/cluster` looks and if we disable some specific path to be mounted inside the apps, what other apps do we want to allow as clearly it means top level `/cluster` should not be allowed as well..

2022-06-20 18:12 UTC, yocalebo commented
In middlewared repo I have a global variable "CTDB_LOCAL_MOUNT" that needs to be excluded from being mounted by any app.

Also, I'm not sure adding /cluster right now is smart. We are making too many changes that could potentially be backwards incompatible and I don't really want to think about 3rd party apps right now.

2022-06-20 18:14 UTC, Qubad786 commented
So in that case should we not allow adding `/cluster` then @yocalebo @sonicaj?

About the local mount, i assume any path except for `/cluster/ctdb_shared_vol` is safe inside `/cluster`?

2022-06-20 18:16 UTC, yocalebo commented
> So in that case should we not allow adding `/cluster` then @yocalebo @sonicaj?
> 
> 
> 
> About the local mount, i assume any path except for `/cluster/ctdb_shared_vol` is safe inside `/cluster`?

Yes, I don't think we should add /cluster right now. Also, I don't want to hardcode the ctdb shared volume fuse mountpoint in this repo. We need to be able to update that singular variable and have everywhere else get updated as expected. But adding /cluster is premature imo and we should hold off until we understand/design/test a little more.

2022-06-22 11:55 UTC, yocalebo commented on library/common/2112.0.0/templates/lib/storage/_hostpathValidation.tpl
> +        {{- if and (eq (index $host_p 0) "mnt") (lt ($host_p | len) 3) -}}
Is it correct syntax to do `if and`?

2022-06-22 12:00 UTC, yocalebo approved these changes
I don't like this but I guess we don't have an option 😄

2022-06-22 12:34 UTC, merged