Allow users to specify their own webui portals for apps
truenas/charts pull request #575
Opened 2022-07-03 17:23 UTC by sonicaj

2022-07-03 17:23 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-115275

2022-07-04 00:13 UTC, Ornias1993 requested changes

2022-07-04 00:13 UTC, Ornias1993 commented on test/ix-chart/2207.1.0/questions.yaml
> +    schema:
might be best to put a dict under this, for easy multi-portal support in the future.
This extra dict layer doesn't have to be used yet, but gives a lot more flexibility.

2022-07-05 13:26 UTC, Qubad786 approved these changes

2022-07-07 08:48 UTC, merged